import type { Finding, HealthResponse, ScanResponse, TlsScanResult } from '@/types';

export const DEMO_PLANTED_FINDINGS: Finding[] = [
  {
    id: 'crypto-rsa-2048-001',
    scanId: 'scan-demo-001',
    projectId: 'demo',
    algorithm: 'RSA-2048',
    displayName: 'RSA (2048-bit key establishment)',
    primitive: 'pke',
    parameter: '2048',
    parameterStatus: 'resolved',
    mode: null,
    curve: null,
    usage: 'key_establishment',
    artefactType: 'key-exchange',
    library: 'PyCryptodome',
    filePath: 'auth.py',
    lineNumber: 42,
    unresolvedParameters: [],
    isQuantumSensitive: true,
    isCurrentlyWeak: false,
    isHndlExposed: true,
    needsVerification: false,
    riskTier: 'overdue',
    createdAt: new Date().toISOString(),
    evidence: {
      filePath: 'auth.py',
      lineNumber: 42,
      endLineNumber: 42,
      codeSnippet: 'key = RSA.generate(2048)\nprivate_key = key.export_key()',
      contextLines: [
        '# Security Module - Authentication & Key Exchange',
        'def initialize_session_keys():',
        '    key = RSA.generate(2048)',
        '    private_key = key.export_key()',
        '    return private_key',
      ],
      detectionMethod: 'semgrep_api_pattern',
      confidence: 0.96,
      confidenceLevel: 'high',
      ruleId: 'blindspot.python.rsa.generate-key',
    },
    classification: {
      artefactType: 'key-exchange',
      securityGoal: 'confidentiality',
      dataLifetimeYears: 15,
      criticality: 'high',
      isLongLivedTrustAnchor: false,
      lifetimeSource: 'regulatory_default (High-value enterprise credentials)',
      rationale: 'Key establishment protecting long-lived sensitive enterprise data (X = 15 years).',
    },
    currentRisk: {
      isCurrentlyWeak: false,
      severity: 'none',
      reason: 'RSA-2048 is currently compliant with NIST SP 800-57 Part 1 Rev. 5 until 2030.',
      references: ['NIST SP 800-57 Part 1'],
    },
    quantumRisk: {
      isQuantumVulnerable: true,
      threat: 'shor_breaks',
      effectiveSecurityLoss: 'Complete breakage via Shor\'s algorithm',
      reason: 'Polynomial-time period finding completely recovers the RSA prime factors.',
    },
    mosca: {
      x: 15,
      y: 3,
      z: 10,
      equation: '15 + 3 > 10',
      result: true,
      tier: 'overdue',
      marginYears: 8,
      zSource: 'CRQC Estimated Horizon (2035)',
      applicable: true,
      notes: 'Data secrecy lifetime (15y) + migration lead time (3y) exceeds quantum horizon (10y). Immediate migration required.',
    },
    recommendation: {
      strategy: 'PQC',
      algorithm: 'ML-KEM-768',
      parameterSet: 'FIPS 203 (ML-KEM-768)',
      rationale: 'Long-lived sensitive data and migration lead time exceed estimated quantum horizon. Immediate replacement with NIST FIPS 203 (ML-KEM-768) required.',
      replaces: 'RSA-2048',
      priority: 1,
      effort: 'Medium (API wrap required)',
      migrationNotes: [
        'Replace RSA key transport with ML-KEM-768 encapsulation.',
        'Update ciphertext storage structures for 1088-byte public key size.',
        'Implement hybrid key negotiation during transitional deployment.',
      ],
      references: ['NIST FIPS 203', 'NIST IR 8547'],
      isQuantumRecommendation: true,
    },
  },
  {
    id: 'crypto-x25519-002',
    scanId: 'scan-demo-001',
    projectId: 'demo',
    algorithm: 'X25519',
    displayName: 'X25519 (ECDH key exchange)',
    primitive: 'key-agree',
    parameter: '256',
    parameterStatus: 'resolved',
    mode: null,
    curve: 'Curve25519',
    usage: 'key_establishment',
    artefactType: 'key-exchange',
    library: 'cryptography.hazmat',
    filePath: 'tls.py',
    lineNumber: 18,
    unresolvedParameters: [],
    isQuantumSensitive: true,
    isCurrentlyWeak: false,
    isHndlExposed: false,
    needsVerification: false,
    riskTier: 'transitional',
    createdAt: new Date().toISOString(),
    evidence: {
      filePath: 'tls.py',
      lineNumber: 18,
      endLineNumber: 18,
      codeSnippet: 'peer_public_key = X25519PublicKey.from_public_bytes(raw_bytes)',
      contextLines: [
        '# TLS Handshake Helper',
        'def perform_ecdh(raw_bytes):',
        '    peer_public_key = X25519PublicKey.from_public_bytes(raw_bytes)',
        '    shared_key = private_key.exchange(peer_public_key)',
        '    return shared_key',
      ],
      detectionMethod: 'semgrep_ast_confirmed',
      confidence: 0.94,
      confidenceLevel: 'high',
      ruleId: 'blindspot.python.ecdh.x25519',
    },
    classification: {
      artefactType: 'key-exchange',
      securityGoal: 'confidentiality',
      dataLifetimeYears: 5,
      criticality: 'medium',
      isLongLivedTrustAnchor: false,
      lifetimeSource: 'config_declared (Short-term session traffic)',
      rationale: 'Active ECDH key exchange protecting medium secrecy lifetime data (X = 5 years).',
    },
    currentRisk: {
      isCurrentlyWeak: false,
      severity: 'none',
      reason: 'X25519 offers 128-bit classical security against current attacks.',
      references: ['RFC 7748'],
    },
    quantumRisk: {
      isQuantumVulnerable: true,
      threat: 'shor_breaks',
      effectiveSecurityLoss: 'Complete breakage via Shor\'s algorithm',
      reason: 'Elliptic curve discrete logarithm is solvable in $O(n^3)$ operations on a quantum computer.',
    },
    mosca: {
      x: 5,
      y: 2,
      z: 10,
      equation: '5 + 2 <= 10',
      result: false,
      tier: 'transitional',
      marginYears: -3,
      zSource: 'CRQC Estimated Horizon (2035)',
      applicable: true,
      notes: 'Timeline allows planned transition. Hybrid deployment recommended to maintain classical compliance while preparing PQC readiness.',
    },
    recommendation: {
      strategy: 'HYBRID',
      algorithm: 'X25519 + ML-KEM-768',
      parameterSet: 'Hybrid KEM (X25519 / ML-KEM-768)',
      rationale: 'Provides a smooth transition path while maintaining classical FIPS compliance and adding quantum resistance.',
      replaces: 'X25519 standalone',
      priority: 2,
      effort: 'Low (Library update)',
      migrationNotes: [
        'Deploy dual-KEM negotiation pattern.',
        'Combine shared secrets using HKDF-SHA256.',
      ],
      references: ['IETF draft-ietf-tls-hybrid-design'],
      isQuantumRecommendation: true,
    },
  },
  {
    id: 'crypto-md5-003',
    scanId: 'scan-demo-001',
    projectId: 'demo',
    algorithm: 'MD5',
    displayName: 'MD5 (Message Digest 5)',
    primitive: 'hash',
    parameter: '128',
    parameterStatus: 'resolved',
    mode: null,
    curve: null,
    usage: 'integrity_hash',
    artefactType: 'hash',
    library: 'hashlib',
    filePath: 'legacy.py',
    lineNumber: 91,
    unresolvedParameters: [],
    isQuantumSensitive: false,
    isCurrentlyWeak: true,
    isHndlExposed: false,
    needsVerification: false,
    riskTier: 'overdue',
    createdAt: new Date().toISOString(),
    evidence: {
      filePath: 'legacy.py',
      lineNumber: 91,
      endLineNumber: 91,
      codeSnippet: 'checksum = hashlib.md5(payload).hexdigest()',
      contextLines: [
        '# Legacy Payload Verification',
        'def compute_checksum(payload):',
        '    checksum = hashlib.md5(payload).hexdigest()',
        '    return checksum',
      ],
      detectionMethod: 'semgrep_api_pattern',
      confidence: 0.99,
      confidenceLevel: 'high',
      ruleId: 'blindspot.python.hash.md5-use',
    },
    classification: {
      artefactType: 'hash',
      securityGoal: 'integrity',
      dataLifetimeYears: 1,
      criticality: 'high',
      isLongLivedTrustAnchor: false,
      lifetimeSource: 'system_default',
      rationale: 'Legacy cryptographic hash used for payload integrity.',
    },
    currentRisk: {
      isCurrentlyWeak: true,
      severity: 'critical',
      reason: 'MD5 suffers from severe collision vulnerabilities ($2^{18}$ complexity) and is broken today.',
      references: ['CWE-328', 'NIST SP 800-131A'],
    },
    quantumRisk: {
      isQuantumVulnerable: false,
      threat: 'none_known',
      effectiveSecurityLoss: 'N/A',
      reason: 'MD5 is already broken classically.',
    },
    mosca: {
      x: 1,
      y: 0.5,
      z: 10,
      equation: 'N/A (Present weakness)',
      result: false,
      tier: 'overdue',
      marginYears: 0,
      zSource: 'N/A',
      applicable: false,
      notes: 'This is a present-day classical vulnerability. Remediation is required immediately regardless of quantum timelines.',
    },
    recommendation: {
      strategy: 'REMEDIATE_NOW',
      algorithm: 'SHA-256',
      parameterSet: 'FIPS 180-4 (SHA-256)',
      rationale: 'MD5 is broken classically due to collision attacks. Replace immediately with SHA-256 or SHA-3.',
      replaces: 'MD5',
      priority: 1,
      effort: 'Low (Drop-in function replacement)',
      migrationNotes: [
        'Replace `hashlib.md5` with `hashlib.sha256`.',
        'Update database checksum column length to 64 hex characters.',
      ],
      references: ['NIST SP 800-131A Rev. 2'],
      isQuantumRecommendation: false,
    },
  },
  {
    id: 'crypto-ecdsa-004',
    scanId: 'scan-demo-001',
    projectId: 'demo',
    algorithm: 'ECDSA',
    displayName: 'ECDSA (P-256 signature)',
    primitive: 'signature',
    parameter: 'P-256',
    parameterStatus: 'resolved',
    mode: null,
    curve: 'secp256r1',
    usage: 'session_signature',
    artefactType: 'signature',
    library: 'cryptography.hazmat',
    filePath: 'signing.py',
    lineNumber: 64,
    unresolvedParameters: [],
    isQuantumSensitive: true,
    isCurrentlyWeak: false,
    isHndlExposed: false,
    needsVerification: false,
    riskTier: 'low-risk',
    createdAt: new Date().toISOString(),
    evidence: {
      filePath: 'signing.py',
      lineNumber: 64,
      endLineNumber: 64,
      codeSnippet: 'sig = private_key.sign(message, ec.ECDSA(hashes.SHA256()))',
      contextLines: [
        '# Short-Lived Session Token Signing',
        'def sign_ephemeral_token(message):',
        '    sig = private_key.sign(message, ec.ECDSA(hashes.SHA256()))',
        '    return sig',
      ],
      detectionMethod: 'semgrep_api_pattern',
      confidence: 0.95,
      confidenceLevel: 'high',
      ruleId: 'blindspot.python.ecdsa.sign',
    },
    classification: {
      artefactType: 'signature',
      securityGoal: 'authenticity',
      dataLifetimeYears: 0.1,
      criticality: 'low',
      isLongLivedTrustAnchor: false,
      lifetimeSource: 'short_lived_session',
      rationale: 'Short-lived ephemeral token signature (X = 0.1 years).',
    },
    currentRisk: {
      isCurrentlyWeak: false,
      severity: 'none',
      reason: 'ECDSA P-256 is secure against classical attacks.',
      references: ['FIPS 186-5'],
    },
    quantumRisk: {
      isQuantumVulnerable: true,
      threat: 'shor_breaks',
      effectiveSecurityLoss: 'Signature forgery on CRQC availability',
      reason: 'Signatures are only vulnerable to real-time forgery when a CRQC is active.',
    },
    mosca: {
      x: 0.1,
      y: 1,
      z: 10,
      equation: '0.1 + 1 <= 10',
      result: false,
      tier: 'low-risk',
      marginYears: -8.9,
      zSource: 'CRQC Estimated Horizon (2035)',
      applicable: true,
      notes: 'Ephemeral signature validity expires rapidly. No store-now-decrypt-later vulnerability applies.',
    },
    recommendation: {
      strategy: 'DEFER',
      algorithm: 'ML-DSA-65 (Future)',
      parameterSet: 'FIPS 204 (ML-DSA-65)',
      rationale: 'Low quantum urgency due to short ephemeral lifetime. Monitor PQC signature standardization and defer active migration.',
      replaces: 'ECDSA P-256',
      priority: 3,
      effort: 'Low (Scheduled roadmap item)',
      migrationNotes: [
        'Monitor NIST FIPS 204 (ML-DSA) adoption in upstream libraries.',
        'Plan migration during scheduled software upgrade cycle.',
      ],
      references: ['NIST FIPS 204'],
      isQuantumRecommendation: true,
    },
  },
  {
    id: 'crypto-rsa-unknown-005',
    scanId: 'scan-demo-001',
    projectId: 'demo',
    algorithm: 'RSA',
    displayName: 'RSA (Key size variable / Unresolved)',
    primitive: 'pke',
    parameter: 'unknown',
    parameterStatus: 'unresolved',
    mode: null,
    curve: null,
    usage: 'key_establishment',
    artefactType: 'key-exchange',
    library: 'PyCryptodome',
    filePath: 'config.py',
    lineNumber: 27,
    unresolvedParameters: ['key_size'],
    isQuantumSensitive: true,
    isCurrentlyWeak: false,
    isHndlExposed: true,
    needsVerification: true,
    riskTier: 'overdue',
    createdAt: new Date().toISOString(),
    evidence: {
      filePath: 'config.py',
      lineNumber: 27,
      endLineNumber: 27,
      codeSnippet: 'KEY_SIZE = config.get("key_size")\nkey = RSA.generate(KEY_SIZE)',
      contextLines: [
        '# Dynamic Configuration RSA Generation',
        'KEY_SIZE = config.get("key_size")',
        'key = RSA.generate(KEY_SIZE)',
        'logger.info(f"Generated RSA key of size {KEY_SIZE}")',
      ],
      detectionMethod: 'semgrep_string_match',
      confidence: 0.65,
      confidenceLevel: 'medium',
      ruleId: 'blindspot.python.rsa.dynamic-key',
    },
    classification: {
      artefactType: 'key-exchange',
      securityGoal: 'confidentiality',
      dataLifetimeYears: 10,
      criticality: 'medium',
      isLongLivedTrustAnchor: false,
      lifetimeSource: 'default_inference',
      rationale: 'RSA key generation with dynamic key size passed via configuration variable.',
    },
    currentRisk: {
      isCurrentlyWeak: false,
      severity: 'medium',
      reason: 'Key size cannot be statically verified; if key_size < 2048, classical security is compromised.',
      references: ['CWE-326'],
    },
    quantumRisk: {
      isQuantumVulnerable: true,
      threat: 'shor_breaks',
      effectiveSecurityLoss: 'Vulnerable regardless of key size',
      reason: 'All RSA key sizes are vulnerable to Shor\'s algorithm.',
    },
    mosca: {
      x: 10,
      y: 2,
      z: 10,
      equation: '10 + 2 > 10',
      result: true,
      tier: 'overdue',
      marginYears: 2,
      zSource: 'CRQC Estimated Horizon (2035)',
      applicable: true,
      notes: 'Unresolved key size parameter flagged for manual investigation. Defaulted to conservative 10-year secrecy lifetime.',
    },
    recommendation: {
      strategy: 'INVESTIGATE',
      algorithm: 'ML-KEM-768 (Pending Audit)',
      parameterSet: 'FIPS 203',
      rationale: 'Parameter status unresolved during static AST scan. Perform runtime configuration audit, enforce min 3072-bit RSA or transition to ML-KEM-768.',
      replaces: 'RSA (Dynamic)',
      priority: 1,
      effort: 'Low (Configuration review)',
      migrationNotes: [
        'Inspect runtime configuration files for `key_size` parameter value.',
        'Enforce key size validation in application startup hooks.',
      ],
      references: ['NIST SP 800-57'],
      isQuantumRecommendation: true,
    },
  },
];

export const DEMO_HEALTH_RESPONSE: HealthResponse = {
  status: 'ok',
  service: 'Blindspot ECDAT API',
  version: '1.0.0',
  environment: 'development',
  phase: 'demo-ready',
  readiness: 'ready',
  degradedSubsystems: [],
  subsystems: {
    firebase: { available: true, reason: 'Firebase Admin SDK connected' },
    semgrep: { available: true, reason: 'Semgrep 1.78.0 ready with custom rules' },
    demoRepository: { available: true, reason: 'Seeded demo repository available at /demo-repo' },
    fallbackCache: { available: true, reason: 'Cached scan fallback available' },
  },
  mosca: {
    activeZ: 10,
    activeZSource: 'CRQC Estimated Horizon (2035)',
    defaultY: 3,
    zPresets: [
      { name: 'CRQC 2035 (Standard)', z: 10, targetYear: 2035, source: 'NIST / CNSA 2.0' },
      { name: 'India CII Regulatory (2028)', z: 3, targetYear: 2028, source: 'India NCIIPC Directive' },
      { name: 'NIST IR 8547 Fast Track (2030)', z: 5, targetYear: 2030, source: 'NIST IR 8547' },
    ],
  },
};

export const DEMO_SCAN_RESPONSE: ScanResponse = {
  scanId: 'scan-demo-001',
  status: 'completed',
  mode: 'live',
  repository: 'f:/blindspot/demo-repo',
  findingCount: 5,
  summary: {
    totalFindings: 5,
    quantumSensitive: 4,
    overdue: 2,
    transitional: 1,
    lowRisk: 1,
    currentWeakCrypto: 1,
    hndlExposed: 2,
    needsVerification: 1,
    unresolvedParameters: 1,
    byAlgorithm: {
      'RSA-2048': 1,
      X25519: 1,
      MD5: 1,
      ECDSA: 1,
      RSA: 1,
    },
    byArtefactType: {
      'key-exchange': 3,
      hash: 1,
      signature: 1,
    },
    byConfidenceLevel: {
      high: 4,
      medium: 1,
    },
    filesScanned: 5,
  },
  durationSeconds: 1.42,
  cbomAvailable: true,
  message: 'Scan completed successfully. 5 planted artefacts discovered and analyzed.',
};

export const DEMO_CBOM_JSON = JSON.stringify(
  {
    bomFormat: 'CycloneDX',
    specVersion: '1.6',
    serialNumber: 'urn:uuid:b590e8d0-23a1-4d37-93e1-889a746a501a',
    version: 1,
    metadata: {
      timestamp: new Date().toISOString(),
      tools: [
        {
          vendor: 'Blindspot Security',
          name: 'ECDAT Scanner',
          version: '1.0.0',
        },
      ],
      component: {
        type: 'application',
        name: 'demo-repo',
        version: '1.0.0',
        'bom-ref': 'demo-repo-root',
      },
    },
    components: DEMO_PLANTED_FINDINGS.map((f) => ({
      type: 'cryptographic-asset',
      name: f.displayName,
      'bom-ref': f.id,
      cryptoProperties: {
        assetType: f.artefactType,
        primitive: f.primitive,
        algorithmProperties: {
          variant: f.algorithm,
          parameterSetIdentifier: f.parameter || 'unknown',
          cryptoFunctions: [f.usage],
        },
        oid: null,
      },
      evidence: {
        occurrences: [
          {
            location: f.filePath,
            line: f.lineNumber,
            symbol: f.evidence.ruleId,
          },
        ],
      },
    })),
  },
  null,
  2,
);

/**
 * A real-shaped TLS scan result used as a clearly-labelled fallback when a live
 * probe cannot reach the target (e.g. restricted demo-room network). It is
 * always presented as "sample", never as a fresh live scan.
 */
export const DEMO_TLS_RESULT: TlsScanResult = {
  host: 'example.com',
  port: 443,
  protocol: 'TLSv1.3',
  protocolSecure: true,
  cipherSuite: 'TLS_AES_256_GCM_SHA384',
  cipherBits: 256,
  certificate: {
    subject: 'CN=example.com',
    issuer: 'CN=DigiCert Global G3 TLS ECC SHA384 2020 CA1',
    notAfter: '2026-03-01T23:59:59Z',
    expired: false,
    signatureAlgorithm: 'ecdsa-with-SHA384',
    keyType: 'ECDSA',
    keyBits: 256,
    curve: 'secp256r1',
  },
  notes: [],
  findings: [DEMO_PLANTED_FINDINGS[3]],
};
